--DROP TABLE IF EXISTS CATEGORY_CHARGES;
--create table CATEGORY_CHARGES(ID INT PRIMARY KEY,
--SOURCE_CATEGORY VARCHAR,
--DESTINATION_CATEGORY VARCHAR,
--PERCENTAGE_CHARGES DOUBLE
--);
--DROP TABLE IF EXISTS LOCATION_CATEGORY;
--create table LOCATION_CATEGORY(ID INT PRIMARY KEY,
--CITY_NAME VARCHAR,
--PIN_CODE VARCHAR,
--CATEGORY VARCHAR
--);
--DROP TABLE IF EXISTS PYMNT_METHOD_HANDLING_CHARGES;
--create table PYMNT_METHOD_HANDLING_CHARGES(ID INT PRIMARY KEY,
--PAYMENT_METHOD VARCHAR,
--HANDLING_CHARGE DOUBLE
--);
--DROP TABLE IF EXISTS WEIGHT_CHARGES;
--create table WEIGHT_CHARGES(ID INT PRIMARY KEY,
--WEIGHT_SLAB VARCHAR,
--CHARGE DOUBLE
--);



INSERT INTO LOCATION_CATEGORY(ID,CITY_NAME,PIN_CODE,CATEGORY) VALUES(1,'DELHI','12456','METRO');
INSERT INTO LOCATION_CATEGORY(ID,CITY_NAME,PIN_CODE,CATEGORY) VALUES(2,'MUMBAI','18656','METRO');

INSERT INTO CATEGORY_CHARGES(ID,SOURCE_CATEGORY,DESTINATION_CATEGORY,PERCENTAGE_CHARGES) VALUES(1,'METRO','METRO',152.25);

INSERT INTO PYMNT_METHOD_HANDLING_CHARGES(ID,PAYMENT_METHOD,HANDLING_CHARGE) VALUES(1,'COD',4.25);

INSERT INTO WEIGHT_CHARGES(ID,WEIGHT_SLAB,CHARGE) VALUES(1,'HEAVY',90.25);


